# Библиотеки NUMPY и Matplotlib
## Сарновский Даниил Вячеславович - НПМбв-02-20
### !!!Пожалуйста, подпишите своё задание - напишите в заголовке ФИО и номер группы

### О задании
Это домашнее задание на библиотеки `numpy` и `matplotlib.pyplot`. В данном задании не рекомендуется использовать циклы, по возможности нужно использовать векторизированные операции `numpy`. Сделанное задание в виде файла с расширением .ipynb (jupyter notebook) нужно загрузить в свой гитхаб репозиторий.  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:   
https://cs.mipt.ru/advanced_python/lessons/lab16.html

### Оценивание и штрафы

Задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов. Если вы нашли решение какого-то из заданий (или его часть) в открытом источнике, необходимо указать ссылку на этот источник в отдельном блоке в конце вашей работы (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник).

Сейчас мы находимся в jupyter-ноутбуке (или ipython-ноутбуке). Это удобная среда для написания кода, проведения экспериментов, изучения данных, построения визуализаций и других нужд, не связанных с написаем production-кода. 

Ноутбук состоит из ячеек, каждая из которых может быть либо ячейкой с кодом, либо ячейкой с текстом размеченным и неразмеченным. Текст поддерживает markdown-разметку и формулы в Latex.

Для работы с содержимым ячейки используется *режим редактирования* (*Edit mode*, включается нажатием клавиши **Enter** после выбора ячейки), а для навигации между ячейками искользуется *командный режим* (*Command mode*, включается нажатием клавиши **Esc**). Тип ячейки можно задать в командном режиме либо с помощью горячих клавиш (**y** to code, **m** to markdown, **r** to edit raw text), либо в меню *Cell -> Cell type*. 

После заполнения ячейки нужно нажать *Shift + Enter*, эта команда обработает содержимое ячейки: проинтерпретирует код или сверстает размеченный текст.

### Формат сдачи
Для сдачи задания получившийся файл \*.ipynb с решением необходимо выложить в свой репозиторий github.

## Exercise 1
1. Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.  
2. Сгенерировать numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....  
3. Создайте массив первых 10 нечетных целых чисел.  
4. Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.  
5. Создайте массив 8 x 8 с шахматной доской из нулей и единиц.  
6. Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.


In [ ]:
import numpy as np

# 1. Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.
x = np.linspace(-1.3, 2.5, 64)
print(x)
# 2. Сгенерировать numpy массив длины 3n, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....
n = 10
arr = np.tile(np.array([1, 2, 3]), n)
print(arr)
# 3. Создайте массив первых 10 нечетных целых чисел.
odd_nums = np.arange(1, 20, 2)
print(odd_nums)
# 4. Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.
zeros_arr = np.zeros((10, 10))
zeros_arr[0, :] = 1
zeros_arr[-1, :] = 1
zeros_arr[:, 0] = 1
zeros_arr[:, -1] = 1
print(zeros_arr)
# 5. Создайте массив 8 x 8 с шахматной доской из нулей и единиц.
chessboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(chessboard)
# 6. Создайте функцию, которая создает n×n матрицу с (i,j)-элементом, равным i+j.
def create_matrix(n):
   i, j = np.meshgrid(np.arange(n), np.arange(n))
   return i + j
print(create_matrix(4))

## Exercise 2  
1. Создайте график $x^2⋅sin(1/x^2)+x$ на интервале $[−1,1]$, используя 250 точек. Не забудьте пометить оси!
2. Создайте semilogy график (с логарифмической шкалой для оси y и линейной шкалой для оси x) относительной разницы  функций $1/(1+x^2)$ и $1/x^2$ на интервале $[5,25]$. (Относительная разница чисел $a$ и $b$ определяется как $|1−a/b|$)
3. В Scipy также есть много менее распространенных специальных функций. Взгляните на обширный список <a href=https://docs.scipy.org/doc/scipy/reference/special.html> здесь</a>! Выберите несколько интересных спец функций, которые вы знаете (или, может быть, не знаете), подставьте несколько чисел и начертите их.  
4. Создайте цветовой график $sin(x)sin(y)$ на интервале $[−π,π]×[−π,π]$.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Создайте график x^2*sin(1/x^2)+x на интервале [-1,1], используя 250 точек. Не забудьте пометить оси!
x = np.linspace(-1, 1, 250)
y = x**2 * np.sin(1/x**2) + x

plt.figure(figsize=(8, 6))
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('$x^2\\sin(1/x^2)+x$')
plt.show()

# 2. Создайте semilogy график (с логарифмической шкалой для оси y и линейной шкалой для оси x) относительной разницы функций 1/(1+x^2) и 1/x^2 на интервале [5,25].
x = np.linspace(5, 25, 1000)
y1 = 1 / (1 + x**2)
y2 = 1 / x**2
rel_diff = np.abs(1 - y1/y2)

plt.figure(figsize=(8, 6))
plt.semilogy(x, rel_diff)
plt.xlabel('x')
plt.ylabel('Relative Difference')
plt.title('Relative Difference of 1/(1+x^2) and 1/x^2')
plt.show()

# 3. Выберите несколько интересных спец функций, которые вы знаете (или, может быть, не знаете), подставьте несколько чисел и начертите их.
from scipy.special import jn, yn, kn

x = np.linspace(0, 10, 100)

plt.figure(figsize=(8, 6))
plt.plot(x, jn(2, x), label='Bessel J_2(x)')
plt.plot(x, yn(2, x), label='Bessel Y_2(x)')
plt.plot(x, kn(2, x), label='Bessel K_2(x)')
plt.xlabel('x')
plt.ylabel('Value')
plt.title('Bessel Functions')
plt.legend()
plt.show()

# 4. Создайте цветовой график sin(x)sin(y) на интервале [-π,π]×[-π,π].
x = np.linspace(-np.pi, np.pi, 100)
y = np.linspace(-np.pi, np.pi, 100)
X, Y = np.meshgrid(x, y)
Z = np.sin(X) * np.sin(Y)

plt.figure(figsize=(8, 6))
plt.contourf(X, Y, Z, levels=20, cmap='RdGy')
plt.colorbar()
plt.xlabel('x')
plt.ylabel('y')
plt.title('$\sin(x)\sin(y)$')
plt.show()

## Exercise 3  
1. Вычислите $cos(x)$ и $sin(x)$ на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.  
2. Создайте случайный массив $3 × 5$ с помощью функции `np.random.rand(3, 5)` и вычислите: сумму всех элементов, сумму строк и сумму столбцов. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент `axis=`)  
3. Создайте случайный массив $5×5$, используя функцию `np.random.rand(5, 5)`. Отсортируйте строки по второму столбцу. Используйте для этого slicing + argsort + indexing.  
4. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие? Найдите сумму диагональных элементов матриц $B$ и $C$. Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать? (подсказка: используйте готовые функции из библиотеки `np.linalg`).  


In [2]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(123456)

# Generate a random integer from 0 to 9
integral_index = np.random.randint(10)
print(f"Selected integral index: {integral_index}")

# ... (the rest of your code remains the same) ...

n = 3  # Choose the desired size for the square matrix
A = np.random.rand(n, n)
B = A.T @ A
C = A @ A.T

print("\nMatrix A:\n", A)
print("\nMatrix B = A^T @ A:\n", B)
print("\nMatrix C = A @ A^T:\n", C)

print("\nSize of B:", B.shape)
print("Size of C:", C.shape)

print("\nSum of diagonal elements of B:", np.trace(B))
print("Sum of diagonal elements of C:", np.trace(C))

print("\nDeterminant of A:", np.linalg.det(A))
print("Determinant of B:", np.linalg.det(B))
print("Determinant of C:", np.linalg.det(C))

print("\nRank of A:", np.linalg.matrix_rank(A))
print("Rank of B:", np.linalg.matrix_rank(B))
print("Rank of C:", np.linalg.matrix_rank(C))

print("\nEigenvalues of B:", np.linalg.eigvals(B))
print("Eigenvalues of C:", np.linalg.eigvals(C))

Random Array:
 [[0.51491326 0.89812542 0.70582013 0.7788297  0.93162252]
 [0.62876717 0.33986723 0.21579343 0.1183306  0.08322246]
 [0.38544475 0.96056166 0.94246028 0.35274215 0.17554597]]

Sum of all elements: 8.032046718731015

Sum of rows:
 [3.82931103 1.38598089 2.8167548 ]

Sum of columns:
 [1.52912518 2.1985543  1.86407383 1.24990246 1.19039094]

Original Array:
 [[0.15880694 0.95409152 0.14046472 0.032378   0.84024167]
 [0.81065392 0.68345145 0.93085108 0.53268473 0.27868376]
 [0.1439426  0.71942442 0.2958854  0.01158726 0.10375503]
 [0.95512326 0.08201431 0.22478974 0.31254334 0.9327722 ]
 [0.48895446 0.51170177 0.62504249 0.50877638 0.15883776]]

Sorted Array:
 [[0.95512326 0.08201431 0.22478974 0.31254334 0.9327722 ]
 [0.48895446 0.51170177 0.62504249 0.50877638 0.15883776]
 [0.81065392 0.68345145 0.93085108 0.53268473 0.27868376]
 [0.1439426  0.71942442 0.2958854  0.01158726 0.10375503]
 [0.15880694 0.95409152 0.14046472 0.032378   0.84024167]]

Matrix A:
 [[0.28013904 0.59

<class 'numpy.linalg.LinAlgError'>: Last 2 dimensions of the array must be square

## Exercise 4    

Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


1. В реализации этих методов цикл `for` для суммирования использовать нельзя.  
2. Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  
3. Необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ в `Markdown` ячейку).
$$2 - 2 \ln(5)$$
5. В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [1]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(1032206778)

# Generate a random integer from 0 to 9
integral_index = np.random.randint(10)
print(f"Selected integral index: {integral_index}")

# Define the integrals
integrals = [
    lambda x: (x**2 + 3) / (x - 2),
    lambda x: (x + 1) / (x**3 - x**2),
    lambda x: np.exp(1 / x**2) / x**3,
    lambda x: np.cos(np.log(x)) / x,
    lambda x: 1 / (x * (1 + np.log(x)**2)),
    lambda x: np.cos(x)**3,
    lambda x: np.cosh(3 * x)**2,
    lambda x: 1 / (x**2 - 2 * x - 8),
    lambda x: 1 / np.sqrt(2 + 3 * x - 2 * x**2),
    lambda x: (2 * x - 1) / (2 * x + 1)
]

# Define the integration limits
limits = [(3, 4), (-2, -1), (1, 2), (1, np.e), (1, np.e), (0, np.pi / 2), (0, 1 / 3), (2, 3), (3 / 4, 2), (0, 2)]

# Define the analytical solutions
analytical_solutions = [
    np.log(3),
    -1 / 2,
    np.exp(1) - np.exp(1 / 4),
    np.sin(1),
    np.log(np.e),
    2 / 3,
    1 / 9 * (3 * np.sqrt(3) * np.sinh(1) + 9 * np.cosh(1) - 10),
    1 / 4,
    np.pi / 3,
    np.log(3)
]

# Select the integral and limits
integral = integrals[integral_index]
a, b = limits[integral_index]
analytical_solution = analytical_solutions[integral_index]

print(f"Integrating f(x) = {integral.__name__}(x) from {a} to {b}")
print(f"Analytical solution: {analytical_solution}")


def rectangle_method(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    dx = (b - a) / n
    return dx * np.sum(f(x[:-1]))


def trapezoidal_method(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    dx = (b - a) / n
    return dx * (0.5 * f(a) + 0.5 * f(b) + np.sum(f(x[1:-1])))


def simpson_method(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    dx = (b - a) / n
    even_sum = np.sum(f(x[2:-1:2]))
    odd_sum = np.sum(f(x[1:-1:2]))
    return dx / 3 * (f(a) + f(b) + 2 * even_sum + 4 * odd_sum)


n = 10
tolerance = 1e-5
error = 1

while error > tolerance:
    rectangle_integral = rectangle_method(integral, a, b, n)
    trapezoidal_integral = trapezoidal_method(integral, a, b, n)
    simpson_integral = simpson_method(integral, a, b, n)

    error = max(abs(rectangle_integral - analytical_solution),
                abs(trapezoidal_integral - analytical_solution),
                abs(simpson_integral - analytical_solution))

    print(f"n = {n}")
    print(f"Rectangle method: {rectangle_integral}")
    print(f"Trapezoidal method: {trapezoidal_integral}")
    print(f"Simpson method: {simpson_integral}")
    print(f"Error: {error}")

    n *= 10

Selected integral index: 1
Integrating f(x) = <lambda>(x) from -2 to -1
Analytical solution: -0.5
n = 10
Rectangle method: 0.07909273133261131
Trapezoidal method: 0.07492606466594463
Simpson method: 0.07535744317529901
Error: 0.5790927313326113
n = 100
Rectangle method: 0.07577641359709017
Trapezoidal method: 0.07535974693042351
Simpson method: 0.07536414420377725
Error: 0.5757764135970902
n = 1000
Rectangle method: 0.07540576758876455
Trapezoidal method: 0.07536410092209787
Simpson method: 0.07536414490349183
Error: 0.5754057675887645
n = 10000
Rectangle method: 0.07536831113041371
Trapezoidal method: 0.07536414446374705
Simpson method: 0.07536414490356184
Error: 0.5753683111304138
n = 100000
Rectangle method: 0.07536456156583038
Trapezoidal method: 0.07536414489916372
Simpson method: 0.07536414490356186
Error: 0.5753645615658304
n = 1000000
Rectangle method: 0.07536418657018451
Trapezoidal method: 0.07536414490351785
Simpson method: 0.07536414490356183
Error: 0.5753641865701845
n = 1

<class 'numpy.core._exceptions._ArrayMemoryError'>: Unable to allocate 763. MiB for an array with shape (100000000,) and data type float64